// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDq01mf2VMHrCbojEkN8o6s1Ce0gDReDE',
    appId: '1:403071108275:web:beb47def902fd6311b9cc6',
    messagingSenderId: '403071108275',
    projectId: 'money-manage-5e7b8',
    authDomain: 'money-manage-5e7b8.firebaseapp.com',
    storageBucket: 'money-manage-5e7b8.firebasestorage.app',
    measurementId: 'G-J1N85TW1CN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-jnOZNq1UI2KLd5KEDBlpZe90-XDaK9g',
    appId: '1:403071108275:android:f3c0cac0175903c61b9cc6',
    messagingSenderId: '403071108275',
    projectId: 'money-manage-5e7b8',
    storageBucket: 'money-manage-5e7b8.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh7oSHnb5KQMsqrDlv3L4riCFveXTwEA0',
    appId: '1:403071108275:ios:a00808a415b6b2d31b9cc6',
    messagingSenderId: '403071108275',
    projectId: 'money-manage-5e7b8',
    storageBucket: 'money-manage-5e7b8.firebasestorage.app',
    iosBundleId: 'com.example.moneyManageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDq01mf2VMHrCbojEkN8o6s1Ce0gDReDE',
    appId: '1:403071108275:web:28a69d9bd5531cd21b9cc6',
    messagingSenderId: '403071108275',
    projectId: 'money-manage-5e7b8',
    authDomain: 'money-manage-5e7b8.firebaseapp.com',
    storageBucket: 'money-manage-5e7b8.firebasestorage.app',
    measurementId: 'G-PM4FNW0R2V',
  );
}
